# Generated by Django 3.2 on 2021-04-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_first_carusel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_second_carusel',
            field=models.BooleanField(default=False),
        ),
    ]
